from pprint import pprint
from lxml import etree
import pandas as pd
from typing import Union
import json
from pathlib import Path
import os
from soso.strategies.spase.spase import (
    SPASE,
    get_information_url,
    get_resource_id,
    get_instrument,
    get_observatory,
)


def getSchemaLocation(root) -> Union[str, None]:
    # print(root.tag)
    attributes = root.attrib
    # key looks like this: {http://www.w3.org/2001/XMLSchema-instance}schemaLocation
    for key, val in attributes.items():
        if "schemaLocation" in key:
            schemaLocation = val
            # print(schemaLocation)
            if ".xsd" in schemaLocation:
                return schemaLocation
            else:
                return None


def getPaths(entry, paths) -> list:
    """Takes the absolute path of a SPASE record directory to be walked
    to extract all SPASE records present. Returns these paths using the
    list parameter paths, which holds the absolute paths generated by
    the function.

    :param entry: A string of the absolute path of the SPASE record directory
                    to be searched/walked to find all SPASE records within.
    :type entry: String
    :param paths: A list to hold absolute paths of all SPASE records found
                    within the given directory
    :type paths: list
    :return: A list containing the absolute paths of all SPASE records found
                within the given directory.
    :rtype: list
    """
    import os

    print(entry)
    if os.path.exists(entry):
        for root, dirs, files in os.walk(entry):
            root = root.replace("\\", "/")
            # if dirs:
            # for dir in dirs:
            # print(f"Dir is {dir}")
            if files:
                with open("./testFile.txt", "w") as f:
                    for file in files:
                        f.write(root + "\n")
                        # print(root)
                        f.write(file + "\n")
                        # print(file)
                        if (
                            ("/NumericalData" in root)
                            or ("/DisplayData" in root)
                            or ("/DisplayOutput" in root)
                            or ("/NumericalOutput" in root)
                            or ("/Catalog" in root)
                            or ("/Observatory" in root)
                            or ("/Instrument" in root)
                            or ("/Collection" in root)
                        ):
                            paths.append(root + "/" + file)
                            f.write(f"Adding {root}/{file} to paths.\n")
    else:
        print(entry + " does not exist")
    return paths


def get_PersonName(metadata: etree.ElementTree) -> str:
    root = metadata.getroot()
    name = ""
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("Person"):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("PersonName"):
            name = child.text
    return name


def get_address(metadata: etree.ElementTree) -> str:
    root = metadata.getroot()
    address = ""
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("Person"):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("Address"):
            address = child.text
    return address


def get_phone(metadata: etree.ElementTree) -> list:
    root = metadata.getroot()
    phone = []
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("Person"):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("PhoneNumber"):
            phone.append(child.text)
    if not phone:
        phone = ""
    return phone


def get_fax(metadata: etree.ElementTree) -> str:
    root = metadata.getroot()
    fax = ""
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("Person"):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("FaxNumber"):
            fax = child.text
    return fax


def get_email(metadata: etree.ElementTree) -> str:
    root = metadata.getroot()
    email = []
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("Person"):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("Email"):
            email.append(child.text)
    if not email:
        email = ""
    return email


def get_ORCiD(metadata: etree.ElementTree) -> str:
    root = metadata.getroot()
    orcidID = ""
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("Person"):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("ORCIdentifier"):
            orcidID = child.text
    return orcidID


def get_orgName(metadata: etree.ElementTree) -> str:
    root = metadata.getroot()
    affiliation = ""
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("Person"):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("OrganizationName"):
            affiliation = child.text
    return affiliation


def get_ROR(metadata: etree.ElementTree) -> str:
    root = metadata.getroot()
    ROR = []
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if (
            elt.tag.endswith("Person")
            or elt.tag.endswith("Instrument")
            or elt.tag.endswith("Observatory")
        ):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("RORIdentifier"):
            ROR.append(child.text)
    if not ROR:
        ROR = ""
    return ROR


def get_RepositoryID(metadata: etree.ElementTree) -> Union[list, None]:
    root = metadata.getroot()
    repoID = []
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("NumericalData") or elt.tag.endswith("DisplayData"):
            desiredRoot = elt
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("AccessInformation"):
            targetChild = child
            # iterate thru children to locate repoID
            for child in targetChild:
                if child.tag.endswith("RepositoryID"):
                    if child.text not in repoID:
                        repoID.append(child.text)
    if not repoID:
        repoID = ""
    return repoID


def get_relativeStop(metadata: etree.ElementTree) -> str:
    root = metadata.getroot()
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("NumericalData") or elt.tag.endswith("DisplayData"):
            desiredRoot = elt
    desiredTag = desiredRoot.tag.split("}")
    SPASE_Location = (
        ".//spase:"
        + f"{desiredTag[1]}/spase:TemporalDescription/spase:TimeSpan/spase:RelativeStopDate"
    )
    stop = metadata.findtext(
        SPASE_Location,
        namespaces={"spase": "http://www.spase-group.org/data/schema"},
    )
    return stop


def get_ins_or_obs_Start_and_Stop(metadata: etree.ElementTree) -> tuple[str, str]:
    root = metadata.getroot()
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("Instrument") or elt.tag.endswith("Observatory"):
            desiredRoot = elt
    desiredTag = desiredRoot.tag.split("}")
    SPASE_Location = ".//spase:" + f"{desiredTag[1]}/spase:OperatingSpan/spase:StopDate"
    stop = metadata.findtext(
        SPASE_Location,
        namespaces={"spase": "http://www.spase-group.org/data/schema"},
    )
    SPASE_Location = (
        ".//spase:" + f"{desiredTag[1]}/spase:OperatingSpan/spase:StartDate"
    )
    start = metadata.findtext(
        SPASE_Location,
        namespaces={"spase": "http://www.spase-group.org/data/schema"},
    )
    if not stop:
        SPASE_Location = (
            ".//spase:" + f"{desiredTag[1]}/spase:OperatingSpan/spase:RelativeStopDate"
        )
        stop = metadata.findtext(
            SPASE_Location,
            namespaces={"spase": "http://www.spase-group.org/data/schema"},
        )
    if not stop:
        stop = ""
    return start, stop


def findMatchInAllXML(record: str, response: str) -> tuple[bool, str]:
    """Scrapes given NASA SPASE record for productKey which matches a "serviceprovider_ID" found
    in the attributes for datasets in all.xml. When a match is found, update the current
    RelativeStopDate to the one reflected in the "timerange_stop" attribute in all.xml,
    according to 'fuzzy' logic, or replace with a StopDate if related mission has ended.
    """
    # P1D, P1M, and P1Y are examples
    # takes SPASE_Path as arg

    import math
    from pathlib import Path

    def findMatch(records: list, matchKey: str) -> Union[str, None]:
        "Finds SPASE record with matching ProductKey value"
        matchFound = False
        for record in records:
            parser = etree.XMLParser(remove_blank_text=True)
            if os.path.isfile(record):
                NASAtree = etree.parse(record, parser)
                NASAroot = NASAtree.getroot()

                # find element in tree to iterate over
                for elt in NASAroot.iter(tag=etree.Element):
                    if elt.tag.endswith("NumericalData") or elt.tag.endswith(
                        "DisplayData"
                    ):
                        desiredRoot = elt

                # get ProductKey to see if match
                # iterate thru children to locate Access Information
                for child in desiredRoot.iter(tag=etree.Element):
                    if child.tag.endswith("AccessInformation"):
                        targetChild = child
                        # iterate thru children to locate AccessURL and Format
                        for child in targetChild:
                            if child.tag.endswith("AccessURL"):
                                targetChild = child
                                # iterate thru children to locate URL
                                for child in targetChild:
                                    # check if URL has a product key
                                    if child.tag.endswith("ProductKey"):
                                        prodKey = child.text
                                        if matchKey.strip() == prodKey.strip():
                                            matchFound = True
                                            return record
        if not matchFound:
            return None

    def get_stopDate(record: str) -> Union[str, None]:
        "Scrape relativeStopDate from given SPASE record"
        stop = None
        parser = etree.XMLParser(remove_blank_text=True)
        if os.path.isfile(record):
            NASAtree = etree.parse(record, parser)
            NASAroot = NASAtree.getroot()

            # find element in tree to search over
            for elt in NASAroot.iter(tag=etree.Element):
                if elt.tag.endswith("NumericalData") or elt.tag.endswith("DisplayData"):
                    desiredRoot = elt

            desiredTag = desiredRoot.tag.split("}")

            SPASE_Location = (
                ".//spase:"
                + f"{desiredTag[1]}/spase:TemporalDescription/spase:TimeSpan/spase:RelativeStopDate"
            )
            stop = NASAtree.findtext(
                SPASE_Location,
                namespaces={"spase": "http://www.spase-group.org/data/schema"},
            )
        return stop

    def normal_round(n: float) -> int:
        "Rounds number up if >.5 and down if <.5"
        if n - math.floor(n) < 0.5:
            return math.floor(n)
        return math.ceil(n)

    def get_mission(record: str) -> Union[list[str], None]:
        "Scrape InstrumentID from given SPASE record"
        missions = []
        instrument = None
        parser = etree.XMLParser(remove_blank_text=True)
        if os.path.isfile(record):
            NASAtree = etree.parse(record, parser)
            NASAroot = NASAtree.getroot()

            # get instrumentID(s) from given record
            # find element in tree to search over
            for elt in NASAroot.iter(tag=etree.Element):
                if elt.tag.endswith("NumericalData") or elt.tag.endswith("DisplayData"):
                    desiredRoot = elt

            desiredTag = desiredRoot.tag.split("}")

            SPASE_Location = ".//spase:" + f"{desiredTag[1]}/spase:InstrumentID"
            instrument = NASAtree.findall(
                SPASE_Location,
                namespaces={"spase": "http://www.spase-group.org/data/schema"},
            )

        # iterate thru instrumentID(s) to get mission names (observatories)
        # fix instrumentID to access corresponding SPASE record in local dir
        if instrument:
            instrumentIDs = []
            home = str(Path.home()).replace("\\", "/")
            for each in instrument:
                instrumentIDs.append(
                    each.replace("spase://", f"{home}/").replace("'", "") + ".xml"
                )
            # loop thru each instrument to find missions
            for each in instrumentIDs:
                if os.path.isfile(each):
                    NASAtree = etree.parse(each, parser)
                    NASAroot = NASAtree.getroot()
                    for elt in NASAroot.iter(tag=etree.Element):
                        if elt.tag.endswith("Instrument"):
                            desiredRoot = elt

                    desiredTag = desiredRoot.tag.split("}")

                    SPASE_Location = (
                        ".//spase:" + f"{desiredTag[1]}/spase:ObservatoryID"
                    )
                    observatory = NASAtree.findtext(
                        SPASE_Location,
                        namespaces={"spase": "http://www.spase-group.org/data/schema"},
                    )
                    if observatory:
                        # append observatory to missions list to be returned
                        path, sep, mission = observatory.rpartition("Observatory/")
                        if mission not in missions:
                            missions.append(mission)
                        # format observatory entry to get observatoryGroupID
                        observatory = (
                            observatory.replace("spase://", f"{home}/").replace("'", "")
                            + ".xml"
                        )
                        # obtain observatoryGroupID
                        if os.path.isfile(observatory):
                            NASAtree = etree.parse(observatory, parser)
                            NASAroot = NASAtree.getroot()
                            for elt in NASAroot.iter(tag=etree.Element):
                                if elt.tag.endswith("Observatory"):
                                    desiredRoot = elt

                            desiredTag = desiredRoot.tag.split("}")

                            SPASE_Location = (
                                ".//spase:"
                                + f"{desiredTag[1]}/spase:ObservatoryGroupID"
                            )
                            observatoryGroup = NASAtree.findtext(
                                SPASE_Location,
                                namespaces={
                                    "spase": "http://www.spase-group.org/data/schema"
                                },
                            )
                            if observatoryGroup:
                                # append observatoryGroup to missions list to be returned
                                path, sep, mission = observatoryGroup.rpartition(
                                    "Observatory/"
                                )
                                if mission not in missions:
                                    missions.append(mission)
        if missions == []:
            missions = None

        return missions

    # format the NASA SPASE records to search thru NASA repo instead of testing repo
    NASA_Records = []
    # for record in records:
    if "Dev/testing" in record:
        record = record.replace("Dev/testing", "")
    NASA_Records.append(record)

    parser = etree.XMLParser(remove_blank_text=True)
    # try:
    tree = etree.parse(response, parser)
    root = tree.getroot()
    changeMade = False
    changeMessage = ""
    desiredRoots = []
    matchKey = ""
    matchRecord = None
    mission = ""
    if "NumericalData" in record:
        _, _, path = record.partition("NumericalData/")
    else:
        _, _, path = record.partition("DisplayData/")
    mission, _, _ = path.partition("/")

    # find element in tree to iterate over
    # <datasite> ID="CDAWeb_HTTPS"
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("datasite") and (
            "CDAWeb_HTTPS" == elt.attrib["ID"] or "SPDF_HTTPS" == elt.attrib["ID"]
        ):
            desiredRoots.append(elt)

    # iterate thru datasets in all.xml
    for desiredRoot in desiredRoots:
        for dataset in desiredRoot:
            if (not dataset.tag.endswith("description")) and (
                dataset.attrib["ID"][0].lower() == mission[0].lower()
            ):
                # print(dataset)
                matchKey = dataset.attrib["serviceprovider_ID"]
                allXML_Stop = dataset.attrib["timerange_stop"]
                # find matching SPASE record
                matchRecord = findMatch(NASA_Records, matchKey)
                # if match
                if matchRecord is not None:
                    return matchKey
    if matchRecord is None:
        matchKey = ""
    return matchKey


def get_parameter_and_quantities(metadata: etree.ElementTree) -> list[dict]:
    # Each object is:
    #   {"name": Name, "alternateName": ParameterKey, "Quantity": "xQuantity:xQuantityVal"}
    variable_measured = []
    param_quantity = ""
    param_name = ""
    key = ""

    root = metadata.getroot()
    # iterate thru xml to get desired info
    for elt in root.iter(tag=etree.Element):
        if (
            elt.tag.endswith("NumericalData")
            or elt.tag.endswith("DisplayData")
            or elt.tag.endswith("DisplayOutput")
            or elt.tag.endswith("NumericalOutput")
            or elt.tag.endswith("Catalog")
        ):
            desiredRoot = elt

    # traverse xml to extract needed info
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("Parameter"):
            qualifier = []
            target_child = child
            for child in target_child:
                try:
                    if child.tag.endswith("Name"):
                        param_name = child.text
                    elif child.tag.endswith("ParameterKey"):
                        key = child.text
                    elif child.tag.endswith("Field"):
                        target_child = child
                        for child in target_child:
                            if child.tag.endswith("FieldQuantity"):
                                param_quantity = f"FieldQuantity:{child.text}"
                            elif child.tag.endswith("Qualifier"):
                                qualifier.append(child.text)
                    elif child.tag.endswith("Particle"):
                        target_child = child
                        for child in target_child:
                            if child.tag.endswith("ParticleQuantity"):
                                param_quantity = f"ParticleQuantity:{child.text}"
                            elif child.tag.endswith("Qualifier"):
                                qualifier.append(child.text)
                    elif child.tag.endswith("Wave"):
                        target_child = child
                        for child in target_child:
                            if child.tag.endswith("WaveQuantity"):
                                param_quantity = f"WaveQuantity:{child.text}"
                            elif child.tag.endswith("Qualifier"):
                                qualifier.append(child.text)
                    elif child.tag.endswith("Mixed"):
                        target_child = child
                        for child in target_child:
                            if child.tag.endswith("MixedQuantity"):
                                param_quantity = f"MixedQuantity:{child.text}"
                            elif child.tag.endswith("Qualifier"):
                                qualifier.append(child.text)
                    elif child.tag.endswith("Support"):
                        target_child = child
                        for child in target_child:
                            if child.tag.endswith("SupportQuantity"):
                                param_quantity = f"SupportQuantity:{child.text}"
                            elif child.tag.endswith("Qualifier"):
                                qualifier.append(child.text)
                except AttributeError:
                    continue
            # most basic entry for variable measured
            entry = {"name": param_name, "quantity": param_quantity}
            """if key:
                entry["alternateName"] = key"""
            if qualifier:
                entry["qualifier"] = qualifier
            variable_measured.append(entry)
    if len(variable_measured) == 0:
        variable_measured = None
    return variable_measured


def findMatchingInsinAllXML(observatory: str, instrument: str, allXMLPath: str):
    parser = etree.XMLParser(remove_blank_text=True)
    # try:
    tree = etree.parse(allXMLPath, parser)
    root = tree.getroot()
    desiredRoots = []
    startAndStops = []
    obsGroups = {}

    # find element in tree to iterate over
    # <datasite> ID="CDAWeb_HTTPS"
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("datasite") and (
            "CDAWeb_HTTPS" == elt.attrib["ID"] or "SPDF_HTTPS" == elt.attrib["ID"]
        ):
            desiredRoots.append(elt)

    # iterate thru datasets in all.xml
    for desiredRoot in desiredRoots:
        for dataset in desiredRoot:
            matchingObs = False
            matchingIns = False
            start = ""
            stop = ""
            insDescription = ""
            obsDescription = ""
            obsGroups = {}
            startAndStops = []
            if not dataset.tag.endswith("description"):
                for elt in dataset.iter(tag=etree.Element):
                    if elt.tag.endswith("observatory"):
                        # allXML_obs = elt.attrib["ID"].upper()
                        targetChild = elt
                        for elt in targetChild.iter(tag=etree.Element):
                            if elt.tag.endswith("description"):
                                obsDescription = elt.attrib["short"]
                    elif elt.tag.endswith("instrument"):
                        allXML_ins = elt.attrib["ID"].upper()
                        if allXML_ins != instrument.upper():
                            break
                        matchingIns = True
                        targetChild = elt
                        for elt in targetChild.iter(tag=etree.Element):
                            if elt.tag.endswith("description"):
                                insDescription = elt.attrib["short"]
                    elif elt.tag.endswith("mission_group"):
                        allXML_obsGrp = elt.attrib["ID"].upper()
                        if allXML_obsGrp != observatory.upper():
                            break
                        matchingObs = True
                        if allXML_obsGrp not in obsGroups.keys():
                            obsGroups[allXML_obsGrp] = ""
                        targetChild = elt
                        for elt in targetChild.iter(tag=etree.Element):
                            if elt.tag.endswith("description"):
                                obsGrpDescription = elt.attrib["short"]
                                if obsGroups[allXML_obsGrp] != obsGrpDescription:
                                    obsGroups[allXML_obsGrp] = obsGrpDescription
                if matchingIns and matchingObs:
                    start = str(dataset.attrib["timerange_start"])
                    stop = str(dataset.attrib["timerange_stop"])
                    if f"{start}, {stop}" not in startAndStops:
                        startAndStops.append(f"{start}, {stop}")
                # print(dataset)
    # if not startAndStops:
    # return None
    return startAndStops, obsDescription, insDescription, obsGroups


def findMatchingObsinAllXML(observatory: str, allXMLPath: str):
    """
    Given an observatory string, find the match in allXML, returning the different dataset
        start and stops, the obs and obsGrp descriptions, and ins descriptions.

    :param observatory: The abbreviated observatory string (ex: "ACE")
    :type observatory: str
    :param allXMLPath: The full path to the all.xml file you wish to use.
    :type allXMLPath: str
    """
    parser = etree.XMLParser(remove_blank_text=True)
    # try:
    tree = etree.parse(allXMLPath, parser)
    root = tree.getroot()
    desiredRoots = []
    startAndStops = {}
    instruments = {}
    obsGrpDescription = ""

    # find element in tree to iterate over
    # <datasite> ID="CDAWeb_HTTPS"
    for elt in root.iter(tag=etree.Element):
        if elt.tag.endswith("datasite") and (
            "CDAWeb_HTTPS" == elt.attrib["ID"] or "SPDF_HTTPS" == elt.attrib["ID"]
        ):
            desiredRoots.append(elt)

    # iterate thru datasets in all.xml
    for desiredRoot in desiredRoots:
        for dataset in desiredRoot:
            matchingObsGrp = False
            start = ""
            stop = ""
            if not dataset.tag.endswith("description"):
                for elt in dataset.iter(tag=etree.Element):
                    if elt.tag.endswith("mission_group"):
                        allXML_obs = elt.attrib["ID"].upper()
                        if allXML_obs != observatory.upper():
                            break
                        matchingObsGrp = True
                        targetChild = elt
                        for elt in targetChild.iter(tag=etree.Element):
                            if elt.tag.endswith("description"):
                                obsGrpDescription = elt.attrib["short"].upper()
                    elif elt.tag.endswith("instrument"):
                        allXML_ins = elt.attrib["ID"].upper()
                        targetChild = elt
                        for elt in targetChild.iter(tag=etree.Element):
                            if elt.tag.endswith("description"):
                                insDescription = elt.attrib["short"].upper()
                    elif elt.tag.endswith("observatory"):
                        allXML_obsGrp = elt.attrib["ID"].upper()
                        targetChild = elt
                        for elt in targetChild.iter(tag=etree.Element):
                            if elt.tag.endswith("description"):
                                obsDescription = elt.attrib["short"].upper()
                if matchingObsGrp:
                    if f"{allXML_obsGrp}/{allXML_ins}" not in instruments.keys():
                        instruments[f"{allXML_obsGrp}/{allXML_ins}"] = (
                            f"{obsDescription} ||||| {insDescription}"
                        )
                    if f"{allXML_obsGrp}/{allXML_ins}" not in startAndStops.keys():
                        startAndStops[f"{allXML_obsGrp}/{allXML_ins}"] = []
                    start = str(dataset.attrib["timerange_start"])
                    stop = str(dataset.attrib["timerange_stop"])
                    # collect all start and stops in a list and then add them all to the obs/ins key of instruments dict
                    # TODO: finish logic here -- add start and stops after or during?
                    if (
                        f"{start}, {stop}"
                        not in startAndStops[f"{allXML_obsGrp}/{allXML_ins}"]
                    ):
                        if startAndStops[f"{allXML_obsGrp}/{allXML_ins}"] == []:
                            startAndStops[f"{allXML_obsGrp}/{allXML_ins}"] = [
                                f"{start}, {stop}"
                            ]
                        else:
                            startAndStops[f"{allXML_obsGrp}/{allXML_ins}"] += [
                                f"{start}, {stop}"
                            ]
                # print(dataset)
    # if not startAndStops:
    # return None
    if obsGrpDescription:
        return startAndStops, {f"{observatory}": obsGrpDescription}, instruments
    else:
        return startAndStops, None, instruments


def get_observatoryGrps_and_urls(
    metadata: etree.ElementTree, path: str
) -> Union[dict, None]:
    """
    Uses the get_instrument function to attempt to retrieve all relevant information
    associated with any ObservatoryID (and ObservatoryGroupID) fields
    found in their related SPASE records in order to be used in the prov-o
    wasGeneratedBy property.

    :param metadata: The SPASE metadata object as an XML tree.
    :param path: The absolute file path of the XML file the user wishes to pull info from.

    :returns:   The name, url, and ResourceID for each observatory related to this dataset,
                formatted as a list of dictionaries.
    """
    observatory = {}
    observatoryGroups = []
    observatory_group_ids = []
    if os.path.isfile(path):
        root = metadata.getroot()
        for elt in root.iter(tag=etree.Element):
            if elt.tag.endswith("Observatory"):
                desired_root = elt
        for child in desired_root.iter(tag=etree.Element):
            if child.tag.endswith("ObservatoryGroupID"):
                observatory_group_ids.append(child.text)
        infoURL = get_information_url(metadata)
        # finally, follow that link to grab name and url from there
        if observatory_group_ids:
            for observatory_group_id in observatory_group_ids:
                record = (
                    str(Path.home()).replace("\\", "/")
                    + "/"
                    + observatory_group_id.replace("spase://", "")
                    + ".xml"
                )
                record = record.replace("'", "")
                # print(f"ObsGrpID record path is {record}")
                if os.path.isfile(record):
                    test_spase = SPASE(record)
                    group_name = test_spase.get_name()
                    group_url = test_spase.get_url()
                    group_infoURL = get_information_url(test_spase.metadata)
                    grpStart, grpStop = get_ins_or_obs_Start_and_Stop(
                        test_spase.metadata
                    )
                    if group_url:
                        entry = {
                            "Group_name": group_name,
                            "Group_identifier": {
                                "Group@id": group_url,
                                "Group_value": observatory_group_id,
                            },
                        }
                        if group_infoURL:
                            entry["Group_url"] = group_infoURL
                        if grpStart:
                            entry["Group_startDate"] = grpStart
                        if grpStop:
                            entry["Group_stopDate"] = grpStop
                        observatoryGroups.append(entry)
        if infoURL and observatoryGroups:
            observatory = {"url": infoURL, "ObservatoryGroups": observatoryGroups}
        elif infoURL:
            observatory = {"url": infoURL}
        elif observatoryGroups:
            observatory = {"ObservatoryGroups": observatoryGroups}
        else:
            observatory = None
    return observatory


def update_log(cwd: str, addition: str, log_file_name: str) -> None:
    """
    Updates a log file with the given addition. Log files currently updated
    using this method are one containing the SPASE repositories needed for the
    metadata conversion to work as intended and another containing all of the
    SPASE records that could not be accessed.

    :param cwd: The current working directory of your workstation.
    :param addition: The addition to the log file, such as the name of the repository
    needed to access the SPASE record or the SPASE record itself.
    """
    if (cwd is not None) and (addition is not None):
        # create test requiredRepos.txt file for testing suite
        if os.path.isfile(f"{cwd}/{log_file_name}.txt"):
            """with open(f"{cwd}/{log_file_name}.txt", "w", encoding="utf-8") as f:
            f.write("This is placeholder text.")"""
            with open(f"{cwd}/{log_file_name}.txt", "r", encoding="utf-8") as f:
                text = f.read()
            if addition not in text:
                with open(f"{cwd}/{log_file_name}.txt", "a", encoding="utf-8") as f:
                    f.write(f"\n{addition}")
        else:
            with open(f"{cwd}/{log_file_name}.txt", "w", encoding="utf-8") as f:
                pass


def main(
    folder,
    printFlag=True,
    desiredProperties=[
        "id",
        "identifier",
        "sameAs",
        "url",
        "name",
        "description",
        "date_published",
        "keywords",
        "creator",
        "citation",
        "temporal_coverage",
        "temporal",
        "spatial_coverage",
        "publisher",
        "distribution",
        "potential_action",
        "variable_measured",
        "funding",
        "license",
        "was_revision_of",
        "was_derived_from",
        "is_based_on",
        "mentions",
        "is_part_of",
        "date_created",
        "date_modified",
        "contributor",
        "instrument",
        "observatory",
        "alternate_name",
        "inLanguage",
        "subject_of",
        "was_generated_by",
    ],
) -> None:
    # list that holds SPASE records already checked
    searched = []
    RIDs = []
    RNames = []
    URLs = []
    Publishers = []
    allObsGrpIDs = []
    ObsIDs = []
    allInsIDs = []
    homeDir = str(Path.home).replace("\\", "/")
    SPASE_paths = []

    # parameter provided is an xml file
    if folder.endswith(".xml"):
        SPASE_paths = [folder]
    # parameter provided was a directory
    # obtains all filepaths to all SPASE records found in given directory
    else:
        SPASE_paths = getPaths(folder, SPASE_paths)
    # print("You entered " + folder)
    if len(SPASE_paths) == 0:
        print("No records found. Returning.")
    else:
        for r, record in enumerate(SPASE_paths):
            if record not in searched:
                # scrape metadata for each record
                statusMessage = f"Extracting metadata from record {r + 1}"
                statusMessage += f" of {len(SPASE_paths)}"
                print(statusMessage)
                print(record)
                print()
                testSpase = SPASE(record)
                parser = etree.XMLParser(remove_blank_text=True)
                tree = etree.parse(record, parser)
                root = tree.getroot()
                for elt in root.iter(tag=etree.Element):
                    if (
                        elt.tag.endswith("Observatory")
                        or elt.tag.endswith("Instrument")
                        or elt.tag.endswith("NumericalData")
                    ):
                        desired_root = elt
                # treeString = etree.tostring(root, pretty_print = True).decode()
                ResourceName = testSpase.get_name()
                id = testSpase.get_id()
                ResourceID = get_resource_id(testSpase.metadata, testSpase.namespaces)
                publisher = testSpase.get_publisher()

                # save info for report
                RIDs.append(ResourceID)
                RNames.append(ResourceName)
                URLs.append(id)
                if publisher:
                    Publishers.append(publisher["name"])
                else:
                    Publishers.append("")
                ObsGrpIDs = []
                InsIDs = []
                # if NumericalData, also extract InstrumentID(s)
                if "NumericalData/" in ResourceID:
                    ins = False
                    for child in desired_root.iter(tag=etree.Element):
                        if child.tag.endswith("InstrumentID"):
                            InsIDs.append(child.text)
                            ins = True
                    if not ins:
                        InsIDs.append("")
                    allInsIDs.append(InsIDs)
                # if Observatory, extract ObservatoryGroup(s)
                if "Observatory/" in ResourceID:
                    obsGrp = False
                    for child in desired_root.iter(tag=etree.Element):
                        if child.tag.endswith("ObservatoryGroupID"):
                            ObsGrpIDs.append(child.text)
                            obsGrp = True
                    if not obsGrp:
                        ObsGrpIDs.append("")
                    allObsGrpIDs.append(ObsGrpIDs)
                # if Instrument, extract Observatory
                if "Instrument/" in ResourceID:
                    for child in desired_root.iter(tag=etree.Element):
                        if child.tag.endswith("ObservatoryID"):
                            ObsIDs.append(child.text)

                # id = testSpase.get_id()
                """url = testSpase.get_url()
                name = testSpase.get_name()
                sameAs = testSpase.get_same_as()
                keywords = testSpase.get_keywords()
                citation = testSpase.get_citation()
                identifier = testSpase.get_identifier()
                creator = testSpase.get_creator()
                publisher = testSpase.get_publisher()
                #contributor = testSpase.get_contributor()
                variable_measured = testSpase.get_variable_measured()
                temporal_coverage = testSpase.get_temporal_coverage()
                spatial_coverage = testSpase.get_spatial_coverage()
                distribution = testSpase.get_distribution()
                potential_action = testSpase.get_potential_action()
                #funding = testSpase.get_funding()
                license = testSpase.get_license()
                date_created = testSpase.get_date_created()
                date_modified = testSpase.get_date_modified()
                date_published = testSpase.get_date_published()
                was_revision_of = testSpase.get_was_revision_of()
                was_derived_from = testSpase.get_was_derived_from()
                was_generated_by = testSpase.get_was_generated_by()
                is_based_on = testSpase.get_is_based_on()
                mentions = get_mentions(testSpase.metadata, record)
                is_part_of = get_is_part_of(testSpase.metadata, record)
                temporal = get_temporal(testSpase.metadata, testSpase.namespaces)
                instrument = get_instrument(testSpase.metadata, record)
                observatory = get_observatory(testSpase.metadata, record)
                alternate_name = get_alternate_name(testSpase.metadata)"""
                inLanguage = "en"

                if printFlag:
                    for property in desiredProperties:
                        if property == "id":
                            print(" @id:", end=" ")
                            print(json.dumps(id, indent=4))
                        elif property == "sameAs":
                            if sameAs is not None:
                                print(" sameAs:", end=" ")
                                print(json.dumps(sameAs, indent=4))
                            else:
                                print("No PriorID(s) were found.")
                        elif property == "url":
                            print(" url:", end=" ")
                            print(json.dumps(url, indent=4))
                        elif property == "name":
                            print(" name:", end=" ")
                            print(json.dumps(name, indent=4))
                        elif property == "keywords":
                            if keywords is None:
                                print("No keywords found")
                            else:
                                print(" keywords:", end=" ")
                                print(json.dumps(keywords, indent=4))
                        elif property == "citation":
                            print(" citation:", end=" ")
                            print(json.dumps(citation, indent=4))
                        elif property == "identifier":
                            print(" identifier:", end=" ")
                            print(json.dumps(identifier, indent=4))
                        elif property == "creator":
                            if creator is not None:
                                print(" creator:", end=" ")
                                print(json.dumps(creator, indent=4))
                            else:
                                print(
                                    "No creators were found according to the priority rules."
                                )
                        elif property == "date_created":
                            if date_created is not None:
                                print(" date_created:", end=" ")
                                print(json.dumps(date_created, indent=4))
                            else:
                                print("No creation date was found.")
                        elif property == "date_modified":
                            # if trigger:
                            # print("This record has incorrect dates.")
                            # else:
                            print(" date_modified:", end=" ")
                            print(json.dumps(date_modified, indent=4))
                            # print("")
                        elif property == "date_published":
                            if date_published is not None:
                                print(" date_published:", end=" ")
                                print(json.dumps(date_published, indent=4))
                            else:
                                print("No publication date was found.")
                        elif property == "publisher":
                            if publisher is not None:
                                print(" publisher:", end=" ")
                                print(json.dumps(publisher, indent=4))
                            else:
                                print("No publisher was found.")
                        elif property == "contributor":
                            # pos 1161-2 in NumericalData
                            if contributor is not None:
                                print(" contributor:", end=" ")
                                print(json.dumps(contributor, indent=4))
                            else:
                                print("No contributors found.")
                        elif (
                            property == "distribution" or property == "potential_action"
                        ):
                            if property == "distribution":
                                if distribution is not None:
                                    print(" distribution:", end=" ")
                                    print(json.dumps(distribution, indent=4))
                                else:
                                    print("No dataDownloads were found")
                            else:
                                if potential_action is not None:
                                    print(" potential_action:", end=" ")
                                    print(json.dumps(potential_action, indent=4))
                        elif property == "temporal_coverage":
                            if temporal_coverage is not None:
                                # if want to make report on how many have stopDates, check by type (stopDate ones are dict)
                                # if type(temporal_coverage) != str:
                                RNames.append(ResourceName)
                                RIDs.append(ResourceID)
                                DOIs.append(url)
                                print(" temporal_coverage:", end=" ")
                                print(json.dumps(temporal_coverage, indent=4))
                            else:
                                print("No start/stop times were found.")
                        elif property == "spatial_coverage":
                            if spatial_coverage is not None:
                                print(" spatial_coverage:", end=" ")
                                print(json.dumps(spatial_coverage, indent=4))
                            else:
                                print("No observed regions were found.")
                                pass
                        elif property == "funding":
                            if funding is not None:
                                print(" funding:", end=" ")
                                print(json.dumps(funding, indent=4))
                            else:
                                print("No funding info was found.")
                        elif property == "license":
                            if license is not None:
                                print(" license:", end=" ")
                                print(json.dumps(license, indent=4))
                            else:
                                print("No license for the dataset was found.")
                        elif property == "was_revision_of":
                            if was_revision_of is not None:
                                if type(was_revision_of) == list:
                                    for each in was_revision_of:
                                        if each["@type"] == "ScholarlyArticle":
                                            raise ValueError("Found an article link")
                                else:
                                    if was_revision_of["@type"] == "ScholarlyArticle":
                                        raise ValueError("Found an article link")
                                print(" prov:was_revision_of:", end=" ")
                                print(json.dumps(was_revision_of, indent=4))
                            else:
                                print("No was_revision_of was found.")
                        elif property == "was_derived_from":
                            if was_derived_from is not None:
                                print(" prov:was_derived_from:", end=" ")
                                print(json.dumps(was_derived_from, indent=4))
                            else:
                                print("No was_derived_from was found.")
                        elif property == "is_based_on":
                            # only 16 in DisplayData have this, none in ACE/EPAM, 6 in NumericalData
                            if is_based_on is not None:
                                if type(is_based_on) == list:
                                    for each in is_based_on:
                                        if each["@type"] == "ScholarlyArticle":
                                            raise ValueError("Found an article link")
                                else:
                                    if is_based_on["@type"] == "ScholarlyArticle":
                                        raise ValueError("Found an article link")
                                print(" schema:is_based_on:", end=" ")
                                print(json.dumps(is_based_on, indent=4))
                            else:
                                print("No is_based_on was found.")
                        elif property == "was_generated_by":
                            if was_generated_by is not None:
                                print(" prov:was_generated_by:", end=" ")
                                print(json.dumps(was_generated_by, indent=4))
                            else:
                                print("No was_generated_by was found.")
                        # only 25 in NumericalData have "ObservedBy" or "PartOf" associationIDs
                        elif property == "mentions":
                            if mentions is not None:
                                if type(mentions) == list:
                                    for each in mentions:
                                        if each["@type"] == "ScholarlyArticle":
                                            raise ValueError("Found an article link")
                                else:
                                    if mentions["@type"] == "ScholarlyArticle":
                                        raise ValueError("Found an article link")
                                print(" schema:mentions:", end=" ")
                                print(json.dumps(mentions, indent=4))
                            else:
                                print("No mentions was found.")
                        elif property == "is_part_of":
                            if is_part_of is not None:
                                if type(is_part_of) == list:
                                    for each in is_part_of:
                                        if each["@type"] == "ScholarlyArticle":
                                            raise ValueError("Found an article link")
                                else:
                                    if is_part_of["@type"] == "ScholarlyArticle":
                                        raise ValueError("Found an article link")
                                print(" schema:isPartOf:", end=" ")
                                print(json.dumps(is_part_of, indent=4))
                            else:
                                print("No is_part_of was found.")
                        elif property == "variable_measured":
                            if variable_measured is not None:
                                print(" variable_measured:", end=" ")
                                print(json.dumps(variable_measured, indent=4))
                            else:
                                print("No parameters found.")
                        elif property == "temporal":
                            if temporal is not None:
                                print(" temporal:", end=" ")
                                print(json.dumps(temporal, indent=4))
                            else:
                                print("No temporal cadence found.")
                        elif property == "instrument":
                            if instrument is not None:
                                if brokenIns:
                                    InsRIDs.append(ResourceID)
                                    InsRNames.append(ResourceName)
                                    InsDOIs.append(id)
                                    allBrokenIns.append(brokenInsLinks)
                                else:
                                    pass
                                print(" instrument:", end=" ")
                                print(json.dumps(instrument, indent=4))
                            else:
                                if brokenIns:
                                    InsRIDs.append(ResourceID)
                                    InsRNames.append(ResourceName)
                                    InsDOIs.append(id)
                                    allBrokenIns.append(brokenInsLinks)
                                print("No InstrumentIDs found.")
                        elif property == "observatory":
                            if observatory is not None:
                                if brokenObs:
                                    ObsRIDs.append(ResourceID)
                                    ObsRNames.append(ResourceName)
                                    ObsDOIs.append(id)
                                    allBrokenObs.append(brokenObsLinks)
                                else:
                                    pass
                                print(" observatory:", end=" ")
                                print(json.dumps(observatory, indent=4))
                            else:
                                if brokenObs:
                                    ObsRIDs.append(ResourceID)
                                    ObsRNames.append(ResourceName)
                                    ObsDOIs.append(id)
                                    allBrokenObs.append(brokenObsLinks)
                                print("No ObservatoryIDs found.")
                        elif property == "alternate_name":
                            if alternate_name is not None:
                                print(" alternate_name:", end=" ")
                                print(json.dumps(alternate_name, indent=4))
                            else:
                                print("No alternateName found.")
                        elif property == "inLanguage":
                            print(" inLanguage:", end=" ")
                            print(json.dumps(inLanguage, indent=4))
                print("Metadata extraction completed")
                print()

                # add record to searched
                searched.append(record)
    return (RIDs, RNames, URLs, Publishers, allInsIDs, allObsGrpIDs, ObsIDs)


# test directories
"""folder = "C:/Users/zboquet/NASA/DisplayData"
(RIDs, RNames, URLs, Publishers, allInsIDs, allObsGrpIDs, ObsGrpIDs) = main(
    folder, False
)"""
folder = "C:/Users/zboquet/NASA/NumericalData"
RIDs2, RNames2, URLs2, Publishers2, allInsIDs2, allObsGrpIDs2, ObsIDs2 = main(
    folder, False
)
print(len(RIDs2))
print(len(RNames2))
print(len(URLs2))
print(len(Publishers2))
print(len(allInsIDs2))
print(len(allObsGrpIDs2))
print(len(ObsIDs2))

# print(str(len(RIDs)) + " is the num in DD and " + str(len(RIDs2)) + " is the num in ND")
folder = "C:/Users/zboquet/SMWG/Instrument"
RIDs3, RNames3, URLs3, Publishers3, allInsIDs3, allObsGrpIDs3, ObsIDs3 = main(
    folder, False
)

folder = "C:/Users/zboquet/SMWG/Observatory"
RIDs4, RNames4, URLs4, Publishers4, allInsIDs4, allObsGrpIDs4, ObsIDs4 = main(
    folder, False
)

"""df_1 = pd.DataFrame(
    {
        "ResourceID": RIDs,
        "ResourceName": RNames,
        "DOI (or URL)": URLs,
        "ResourceType": "DisplayData",
        "Publisher": Publishers,
        "ProductKey(s)": ProductKeys
    }
)"""
df_2 = pd.DataFrame(
    {
        "ResourceID": RIDs2,
        "ResourceName": RNames2,
        "DOI (or URL)": URLs2,
        "Publisher": Publishers2,
        "InstrumentID(s)": allInsIDs2,
    }
)
df_3 = pd.DataFrame(
    {
        "ResourceID": RIDs3,
        "ResourceName": RNames3,
        "DOI (or URL)": URLs3,
        "Publisher": Publishers3,
        "ObservatoryID": ObsIDs3,
    }
)
df_4 = pd.DataFrame(
    {
        "ResourceID": RIDs4,
        "ResourceName": RNames4,
        "DOI (or URL)": URLs4,
        "Publisher": Publishers4,
        "ObservatoryGroupID(s)": allObsGrpIDs4,
    }
)
with pd.ExcelWriter(
    "C:/Users/zboquet/Documents/SPASE Reports/ClassifyNASA_Ins&Obs.xlsx"
) as writer:
    # use to_excel function and specify the sheet_name and index
    # to store the dataframe in specified sheet
    # df_1.to_excel(writer, sheet_name="DisplayData", index=False)
    df_2.to_excel(writer, sheet_name="NumericalData", index=False)
    df_3.to_excel(writer, sheet_name="Instrument", index=False)
    df_4.to_excel(writer, sheet_name="Observatory", index=False)
