from pprint import pprint
from lxml import etree
import pandas as pd
from pathlib import Path
import os
import re
from soso.strategies.spase.spase import (
    SPASE,
    get_information_url,
    get_resource_id,
    get_instrument,
    get_observatory,
)

def getPaths(entry, paths) -> list:
    """Takes the absolute path of a SPASE record directory to be walked
    to extract all SPASE records present. Returns these paths using the
    list parameter paths, which holds the absolute paths generated by
    the function.

    :param entry: A string of the absolute path of the SPASE record directory
                    to be searched/walked to find all SPASE records within.
    :type entry: String
    :param paths: A list to hold absolute paths of all SPASE records found
                    within the given directory
    :type paths: list
    :return: A list containing the absolute paths of all SPASE records found
                within the given directory.
    :rtype: list
    """
    import os

    print(entry)
    if os.path.exists(entry):
        for root, dirs, files in os.walk(entry):
            root = root.replace("\\", "/")
            # if dirs:
            # for dir in dirs:
            # print(f"Dir is {dir}")
            if files:
                with open("./testFile.txt", "w") as f:
                    for file in files:
                        f.write(root + "\n")
                        # print(root)
                        f.write(file + "\n")
                        # print(file)
                        if (
                            ("/NumericalData" in root)
                            or ("/DisplayData" in root)
                            or ("/DisplayOutput" in root)
                            or ("/NumericalOutput" in root)
                            or ("/Catalog" in root)
                            or ("/Observatory" in root)
                            or ("/Instrument" in root)
                            or ("/Collection" in root)
                        ):
                            paths.append(root + "/" + file)
                            f.write(f"Adding {root}/{file} to paths.\n")
    else:
        print(entry + " does not exist")
    return paths


def main(folder) -> None:
    # list that holds SPASE records already checked
    searched = []
    RIDs = []
    RNames = []
    URLs = []
    allAltNames = []
    homeDir = str(Path.home).replace("\\", "/")
    SPASE_paths = []

    # parameter provided is an xml file
    if folder.endswith(".xml"):
        SPASE_paths = [folder]
    # parameter provided was a directory
    # obtains all filepaths to all SPASE records found in given directory
    else:
        SPASE_paths = getPaths(folder, SPASE_paths)
    # print("You entered " + folder)
    if len(SPASE_paths) == 0:
        print("No records found. Returning.")
    else:
        for r, record in enumerate(SPASE_paths):
            if record not in searched:
                # scrape metadata for each record
                statusMessage = f"Extracting metadata from record {r + 1}"
                statusMessage += f" of {len(SPASE_paths)}"
                print(statusMessage)
                print(record)
                print()
                # create soso object of XML file so can use extraction functions
                testSpase = SPASE(record)
                # parse XML file itself into etree obj
                parser = etree.XMLParser(remove_blank_text=True)#,remove_comments=True)
                tree = etree.parse(record, parser)
                root = tree.getroot()
                # locate XML root needed as params for some extraction functions in spase.py or to
                #   iterate on in this script to extract things not covered in extraction
                #   functions
                for elt in root.iter(tag=etree.Element):
                    if (
                        elt.tag.endswith("Observatory")
                        or elt.tag.endswith("Instrument")
                        or elt.tag.endswith("NumericalData")
                    ):
                        desired_root = elt
                # treeString = etree.tostring(root, pretty_print = True).decode()
                # include calls to related extraction functions in spase.py here
                ResourceName = testSpase.get_name()
                id = testSpase.get_id()
                ResourceID = get_resource_id(testSpase.metadata, testSpase.namespaces)

                # save info for report
                RIDs.append(ResourceID)
                RNames.append(ResourceName)
                URLs.append(id)
                
                altNames = []
                # Can either make custom logic below to extract AlternateName
                #   OR adjust existing get_alternate_name function in spase.py
                #   to work with Observatory records and call that instead
                # if Observatory, extract AlternateNames(s)
                # adjust code below to do this
                if "Observatory/" in ResourceID:
                    alt = False
                    for child in desired_root.iter(tag=etree.Element):
                        if child.tag.endswith("ResourceHeader"):
                            targetChild = child
                            for child in targetChild:
                                #print(child.tag)
                                if child.tag.endswith("AlternateName"):
                                    #print(child)
                                    #print(child.text)
                                    altNames.append(child.text)
                                    alt = True  
                    if not alt:
                        print("No alternate name found")
                        # add empty string to make DataFrames same size
                        altNames.append("")
                    allAltNames.append(altNames)

                print("Metadata extraction completed")
                print()

                # add record to searched
                searched.append(record)
    return (RIDs, RNames, allAltNames, URLs)


# call main with folder containing SPASE records you wish to create report on
folder = "C:/Users/Jimmy/SMWG/Observatory"
RIDs, RNames, allAltNames, URLs = main(folder)
# find lengths of returned lists to determine which is not the same size as the rest if error occurs
print(len(RIDs))
print(len(RNames))
print(len(allAltNames))
print(len(URLs))

# save returned lists to pandas df
df_1 = pd.DataFrame(
    {
        "ResourceID": RIDs,
        "ResourceName": RNames,
        "AlternateName": allAltNames,
        "DOI (or URL)": URLs
    }
)
# change fileName to something more appropriate to what you are doing (e.g. allObsAlternateNames.xlsx)
with pd.ExcelWriter(
    "C:/Users/Jimmy/jimmy_spase/Obs_AltNames_new.xlsx"
) as writer:
    # use to_excel function and specify the sheet_name and index
    # to store the dataframe in specified sheet
    df_1.to_excel(writer, sheet_name="Observatory", index=False)

#main(folder)
#main('C:/Users/Jimmy/SMWG/Observatory/WDC/Faraday.Islands.xml')