# Code utilizes and modifies functionality developed by Zach Boquet
# (https://github.com/Kurokio, zach.c.boquet@nasa.gov) for updating 
# SPASE metadata records

import lxml
from lxml import etree
import xml.etree.ElementTree as ET
import os
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
from pathlib import Path
import subprocess
from soso.strategies.spase.spase import SPASE, get_resource_id

# Establish filepath to home directory
homeDir = str(Path.home()).replace("\\", "/")

def getPaths(entry, paths) -> list:
    """Takes the absolute path of a SPASE record directory to be walked
    to extract all SPASE records present. Returns these paths using the
    list parameter paths, which holds the absolute paths generated by
    the function.

    :param entry: A string of the absolute path of the SPASE record directory
                    to be searched/walked to find all SPASE records within.
    :type entry: String
    :param paths: A list to hold absolute paths of all SPASE records found
                    within the given directory
    :type paths: list
    :return: A list containing the absolute paths of all SPASE records found
                within the given directory.
    :rtype: list
    """
    if os.path.exists(entry):
        for root, dirs, files in os.walk(entry):
            if files:
                for file in files:
                    root = root.replace("\\", "/")
                    paths.append(root + "/" + file)
    else:
        print(entry + " does not exist")
    return paths

def updateRevisions(desiredRoot: etree.ElementTree, note:str) -> None:
    oldDate = updateRelease(desiredRoot)
    oldDateCleaned = oldDate.replace("T", " ").replace("Z", "")
    if '.' in oldDateCleaned:
        oldDate_dt = datetime.strptime(oldDateCleaned, "%Y-%m-%d %H:%M:%S.%f")
    else:
        oldDate_dt = datetime.strptime(oldDateCleaned, "%Y-%m-%d %H:%M:%S")
    # allow 1 second buffer for longer/bigger edits
    oldDate_dt_plus1Sec = oldDate_dt + timedelta(seconds=1)
    found = False
    RevisionHistory = []
    # iterate thru to add another (or new) RevisionHistory event
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("ResourceHeader"):
            targetChild = child
    # check to see if RevisionHistory container is already present
    childrenElts = list(targetChild)
    #print(childrenElts)
    for child in targetChild.iter(tag=etree.Element):
        try:
            if child.tag.endswith("RevisionHistory"):
                found = True
                RH_Child = child
        except AttributeError as err:
            continue
    if found:
        # get all dates in RevHistory
        for child in RH_Child:
            REChild = child
            for child in REChild:
                if child.tag.endswith("ReleaseDate"):
                    date, sep, time = child.text.partition("T")
                    if "Z" in child.text:
                        time = time.replace("Z", "")
                    dt_string = date + " " + time
                    try:
                        if "." in child.text:
                            dt_obj = datetime.strptime(dt_string,
                                                "%Y-%m-%d %H:%M:%S.%f")
                        else:
                            dt_obj = datetime.strptime(dt_string,
                                                    "%Y-%m-%d %H:%M:%S")
                    # catch error when RevisionHistory is not formatted w time
                    except ValueError as err:
                        dt_obj = datetime.strptime(dt_string.strip(),
                                                "%Y-%m-%d").date()
                    finally:
                        RevisionHistory.append(dt_obj)

        # make sure oldDate is recorded in RevHistory
        #print(str(RevisionHistory))
        #print(oldDate_dt)
        if (oldDate_dt not in RevisionHistory) and (oldDate_dt_plus1Sec not in RevisionHistory):
            # find where date is supposed to be and add it
            RevisionHistory.append(oldDate_dt)
            RevisionHistory.sort()
            index = RevisionHistory.index(oldDate_dt)

            if index == 0:
                newNote = "Only known prior ReleaseDate of the metadata"
            else:
                # find note associated with this date
                raise ValueError("Need to dig into Github history to find proper note for this ReleaseDate.")
            RH_Child.insert(index, etree.Element("RevisionEvent"))
            revEventElt = RH_Child[index]
            if oldDate_dt.microsecond == 0:
                originalDate = oldDate_dt.isoformat("T", "seconds")
                newDate = originalDate + "Z"
            # if old date has milliseconds
            else:
                originalDate = oldDate_dt.isoformat("T", "milliseconds")
                newDate = originalDate + "Z"
            etree.SubElement(revEventElt, "ReleaseDate").text = newDate
            etree.SubElement(revEventElt, "Note").text = newNote

        # add today's date as event
        revisionChild = etree.SubElement(RH_Child, "RevisionEvent")
        now = datetime.now().isoformat("T", "seconds")
        newDate = now + "Z"
        etree.SubElement(revisionChild, "ReleaseDate").text = newDate
        etree.SubElement(revisionChild, "Note").text = note
    else:
        # get index of ReleaseDate elt, so can insert a new child for RevHist
        for child in targetChild.iter(tag=etree.Element):
            try:
                if child.tag.endswith("ReleaseDate"):
                    index = childrenElts.index(child) + 1
            except AttributeError as err:
                continue
        targetChild.insert(index, etree.Element("RevisionHistory"))
        revHistoryElt = targetChild[index]
        #print(revHistoryElt)
        # add event for original ReleaseDate
        revisionChild1 = etree.SubElement(revHistoryElt, "RevisionEvent")
        etree.SubElement(revisionChild1, "ReleaseDate").text = oldDate
        etree.SubElement(revisionChild1, "Note").text = "Only known prior ReleaseDate of the metadata"
        # add event for new revisions
        revisionChild = etree.SubElement(revHistoryElt, "RevisionEvent")
        now = datetime.now().isoformat("T", "seconds")
        newDate = now + "Z"
        etree.SubElement(revisionChild, "ReleaseDate").text = newDate
        etree.SubElement(revisionChild, "Note").text = note

def updateRelease(desiredRoot:etree.ElementTree) -> str:
    now = datetime.now().isoformat("T", "seconds")
    newDate = now + "Z"
    for child in desiredRoot.iter(tag=etree.Element):
        if child.tag.endswith("ResourceHeader"):
            targetChild = child
            for child in targetChild:
                try:
                    if child.tag.endswith("ReleaseDate"):
                        oldDate = child.text
                        child.text = newDate
                except AttributeError as err:
                    continue
    return oldDate

def nameReplace(desiredRoot: etree.ElementTree) -> tuple[bool, str]:
    """Replace name in PersonID element

    :param desiredRoot: A string of the absolute path of the SPASE 
                        record directoryto be searched/walked to find all 
                        SPASE records within.
    :type entry: String
    :return: A tuple with boolean (changeMade) and string (changeMessage)
    :rtype: tuple
    """
    # NumericalData > ResourceHeader > Contact > PersonID
    #  
    # > spase://SMWG/Person/Dennis.Haggerty
    # Counter
    a = 0
    
    # Iterate over root to find and replace PersonID field
    for child in desiredRoot.iter(tag=etree.Element):
        a += 1
        if child.tag.endswith("ResourceHeader"):
            targetChild = child
            for child in targetChild:
                if child.tag.endswith("Contact"):
                    targetChild = child
                    for child in targetChild:
                        if child.tag.endswith("PersonID"):
                            if child.text.endswith("Haggerty"):
                                print(child.text)
                                child.text = child.text.replace("Dennis.",
                                                                "Dennis.K.")
                                print(child.text)
    changeMade = True
    changeMessage = "Updated PersonID for Dennis Haggerty to " \
                    "include middle initial (K)."
    print(changeMessage)
    print('\n')
    return changeMade, changeMessage

def addHelioData(desiredRoot: etree.ElementTree, metadata: etree.ElementTree):
    """Add HelioData links as InformationURLs to SPASE records for 
        better interlinking
    
    :param desiredRoot: A string of the absolute path of the SPASE record 
                        directory to be searched/walked to find all SPASE 
                        records within.
    :type entry: String
    :return: A tuple with boolean (changeMade) and string (changeMessage)
    :rtype: tuple
    """
    changeMade = False
    changeMessage = ""
    #dataLicenseAdded = False
    index = None
    namespaces = {"spase": "http://www.spase-group.org/data/schema"}
    """
    Replace the first part of SPASE ResourceID up to “NumericalData/” with 
    “https://helio.data.nasa.gov/dataset/” and replace the remaining slashes 
    with underscores. 
    (e.g. https://spase-metadata.org/NASA/NumericalData/MMS/1/FIELDS/FGM/Survey/Level2/PT0.125S -> https://helio.data.nasa.gov/dataset/MMS_1_FIELDS_FGM_Survey_Level2_PT0.125S)

    SPASE -> HelioData mission page blueprint: “https://helio.data.nasa.gov/mission/” + SPASE Observatory file name without the ‘.xml/.html’ (e.g. https://spase-metadata.org/SMWG/Observatory/MMS.html → https://helio.data.nasa.gov/mission/MMS). Will need to check Observatory folders in SMWG and NASA repos since some observatories (such as AeroCube-6) are not in SMWG.

    For ones found in subdirectories, include each subdirectory with an underscore separating them. (e.g https://spase-metadata.org/SMWG/Observatory/Ground/NASA.Stennis.Space.Center.html → https://helio.data.nasa.gov/mission/Ground_NASA.Stennis.Space.Center) .
    """

    # Get tag of desiredRoot
    desired_tag = desiredRoot.tag.split("}")

    # Select appropriate HelioData directory
    suffix = ""
    if desired_tag[1] == "NumericalData":
        suffix = "dataset"
    elif desired_tag[1] == "Observatory":
        suffix = "mission"

    # Access ResourceID field to recreate SPASE URL
    ResourceID = desiredRoot.find("spase:ResourceID",namespaces=namespaces)
    
    # Get SPASE URL from ResourceID
    spaseURL = ResourceID.text

    # Convert SPASE URL to corresponding HelioData URL
    helioURL_base = f"https://helio.data.nasa.gov/{suffix}/"
    helioFile = spaseURL.partition(f"{desired_tag[1]}/")[2].replace('/','_')
    helioURL = helioURL_base + helioFile

    # Access ResourceHeader to find its subelements (i.e. InformationURL)
    ResourceHeader = desiredRoot.find("spase:ResourceHeader",
                                      namespaces=namespaces)
    """# Verify ResourceHeader is in SPASE record
    if ResourceHeader is not None:
        childrenElts = list(ResourceHeader)
        print(f"Found {len(childrenElts)} children in ResourceHeader")
    else:
        print("No ResourceHeader found.")"""

    # Create new InformationURL element for HelioData
    newInfoURL = etree.Element("InformationURL")

    # Find all InformationURLs already in SPASE record
    InfoURLs = ResourceHeader.findall("spase:InformationURL",
                                      namespaces=namespaces)
    
    # If record has InformationURL objects already, place new one at the end
    if InfoURLs:
        print(f"Found {len(InfoURLs)} InformationURLs. Adding new InformationURL.")
        #index = childrenElts.index(InfoURLs[-1])
        InfoURLs[-1].addnext(newInfoURL)

    # If record does not have InformationURL objects already, insert a new one
    else:
        print("No prior InformationURLs. Inserting after last Contact.")

        # Find all Contacts in SPASE record and append new InfoURL
        Contacts = ResourceHeader.findall("spase:Contact",
                                          namespaces=namespaces)
        Contacts[-1].addnext(newInfoURL)
    
    # Insert HelioData link in InformationURL
    etree.SubElement(newInfoURL, "Name").text = "HelioData"
    etree.SubElement(newInfoURL, "URL").text = helioURL
    etree.SubElement(newInfoURL, "Description").text = "The HelioData mission page provides an overview of the mission and more, such as all SPASE dataset records associated with it."

    # Reflect that HelioData URL was added to SPASE record
    changeMade = True
    changeMessage = "Added HelioData InformationURL"
    
    return changeMade, changeMessage

def main(folders, permanent=False, IDsProvided=False) -> None:
    # list that holds SPASE records already checked
    searched = []
    i = 0
    SPASE_paths = []
    correctedDfRows = []
    changes = 0

    homeDir = str(Path.home()).replace("\\", "/")

    if IDsProvided:
        """Obtain all filepaths to all SPASE records found in the 
            given list of ResourceIDs"""
        for folder in folders:
            if "spase://" in folder:
                formattedRecord = folder.replace("spase://", f"{homeDir}/")
            else:
                formattedRecord = homeDir + "/" + folder
            if not formattedRecord.endswith('.xml'):
                formattedRecord += ".xml"
            SPASE_paths.append(formattedRecord)
    else:
        SPASE_paths = getPaths(folders, SPASE_paths)
    #print("You entered " + folder)
    if len(SPASE_paths) == 0:
        print("No records found. Returning.")
    else:
        print("The number of records is " + str(len(SPASE_paths)))
        # iterate through all SPASE records
        for r, record in enumerate(SPASE_paths):
            if record not in searched:
                changeMessage1 = ""
                changeMessage2 = ""
                changeMessage3 = ""
                changeMessage4 = ""
                changeMade = False
                changeMade2 = False
                changeMade3 = False
                changeMade4 = False
                # scrape metadata for each record
                print()
                print(str(r) + ": " + record)
                parser = etree.XMLParser(remove_blank_text=True, remove_comments=True)
                try:
                    # Define the namespace URI
                    NAMESPACE_URI = "http://www.spase-group.org/data/schema"
                    # Register the namespace with a desired prefix
                    ET.register_namespace("", NAMESPACE_URI)

                    #tree = etree.parse(record, parser)
                    tree = ET.parse(record, parser)
                    root = tree.getroot()

                    # find element in tree to iterate over
                    validRoots = ["NumericalData", "DisplayData", "Observatory", "Instrument",
                                    "NumericalOutput", "DisplayOutput", "Annotation", "Repository",
                                    "Catalog", "Collection", "Document", "Service"]
                    for elt in root.iter(tag=etree.Element):
                        for validRoot in validRoots:
                            if (elt.tag.endswith(validRoot)):
                                desiredRoot = elt

                    # call to correction scripts here
                    # make file reflect the change made in this script
                    #print(record)
                    #changeMade, changeMessage1 = nameReplace(desiredRoot)
                    changeMade, changeMessage1 = addHelioData(desiredRoot,tree)
                    if changeMade:
                        changeMessage = changeMessage1 + '. JWL'
                        
                        # update dates and adds a RevisionHistory/Note text (if doing new correction)
                        updateRevisions(desiredRoot, changeMessage)

                        # add record that was changed to tracking list
                        if changeMade:
                            correctedDfRows.append(record)
                            #pass

                        """
                        # make file reflect the change made in this script
                        #print(record)
                        abs, sep, pathToFile = record.partition("zboquet/")
                        pathToFile, _, fileName = pathToFile.rpartition("/")
                        
                        try:
                            os.makedirs(f"../testing/{pathToFile}")
                        except FileExistsError:
                            pass
                        # update in testing repo
                        #tree.write(f"../testing/{pathToFile}/{fileName}", encoding="UTF-8", xml_declaration=True)
                        """
                        
                        # saving file to f and rewriting with updates
                        f = open(f"{record}", "wb")
                        update = etree.tostring(root, pretty_print=True, encoding="UTF-8", xml_declaration=True)
                        f.write(update)
                        f.close()

                        # validate them before pushing to NASA repo
                        cwd = str(Path.cwd()).replace("\\", "/")
                        print(cwd)
                        # CHANGE homeDir
                        xsdFile = f"{cwd}/spase-latest.xsd"
                        
                        # change to filepath
                        validationScript = f'"{homeDir}/HDRL-Internship-2026/update_records/validate.php"'.strip()
                        print(f"Executing `php {validationScript} {xsdFile} {record}`")
                        proc = subprocess.Popen(f"{homeDir}/php/php.exe {validationScript} {xsdFile} {record}", shell=True, stdout=subprocess.PIPE, cwd=homeDir)
                        script_response = str(proc.stdout.read(), "utf-8").strip()
                        print(script_response)
                        if script_response != 'Validation success':
                            print(f"Skipping {record} since it failed validation")
                            raise RuntimeError("Failed validation!")

                        if permanent:
                            # update in NASA repo
                            f2 = open(record, "wb")
                            f2.write(update)
                            f2.close()

                        # print message for user
                        statusMessage = f"Correcting metadata from record {r+1}"
                        statusMessage += f" of {len(SPASE_paths)}"
                        print(statusMessage)
                        print("The xml file has been updated with the desired changes.")

                        # add 1 to change counter
                        changes += 1

                    # add record to searched
                    searched.append(record)
                    i += 1
                except lxml.etree.XMLSyntaxError:
                    continue
    print(f"{changes} updates were made.")
    print()
    return correctedDfRows

# Path to list of incorrect files
#updateList = Path(homeDir+"/jimmy_spase/haggerty_incorrect.txt").read_text().splitlines()
#main(updateList, IDsProvided=True)

folders = Path(homeDir+"/NASA/NumericalData/")

main(folders)